name: Release Trainer

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  SOLUTION_PATH: 'TFLitePoseTrainer.sln'
  PROJECT_PATH: 'src\TFLitePoseTrainer.csproj'
  DOTNET_VERSION: '9.0.x'

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        device-type: [azure, femto]

    runs-on: windows-latest

    env:
      ARTIFACT_NAME: 'TFLitePoseTrainer-${{ github.ref_name }}-win-x64-${{ matrix.device-type }}'

    steps:
    - name: ‚¨áÔ∏è Checkout Repository
      uses: actions/checkout@v5

    - name: ‚öôÔ∏è Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: üõ†Ô∏è Publish WPF Application
      run: dotnet publish ${{ env.PROJECT_PATH }} -p:DeviceType=${{ matrix.device-type }} -c Release --no-self-contained -o Dest

    - name: üìÅ Archive Release Artifacts
      run: Compress-Archive -Path Dest/* -Destination ${{ env.ARTIFACT_NAME }}.zip

    - name: üöÄ Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.ARTIFACT_NAME }}.zip
        generate_release_notes: true
